export const INCREMENTAR = 'INCREMENTAR'
export const DECREMENTAR = 'DECREMENTAR'
export const ACTUALIZAR_CONTADOR = 'ACTUALIZAR_CONTADOR'


export const SACAR_PRODUCTO = 'SACAR_PRODUCTO'
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS'
export const PRODUCTOS_CARGADOS = 'PRODUCTOS_CARGADOS'